#include <bits/stdc++.h>
using namespace std;

// ------------------------------------------------------------
// Word Ladder II - Optimized Approach
// ------------------------------------------------------------
// Idea:
// 1. Use BFS to find the shortest level (distance)
//    of every reachable word from beginWord.
//
// 2. Use DFS Backtracking from endWord -> beginWord
//    using the levels generated by BFS.
//
// Why this works?
// ----------------
// BFS guarantees shortest distance in an unweighted graph.
//
// During DFS:
// We only move to a word whose level is:
// currentLevel - 1
//
// This ensures:
// - We generate ONLY shortest paths
// - We generate ALL shortest paths
//
// ------------------------------------------------------------

//  N is Number of nodes
//  M is Number of Edges
unordered_map<string, int> mpp;
vector<vector<string>> ans;
string beginW;
int sz;

void dfs(string word, vector<string> &seq) {
  if (word == beginW) {
    reverse(seq.begin(), seq.end());
    ans.push_back(seq);
    reverse(seq.begin(), seq.end());

    return;
  }
  int steps = mpp[word];
  for (int i = 0; i < sz; i++) {
    char original = word[i];

    for (char ch = 'a'; ch <= 'z'; ch++) {
      if (ch == original) {
        continue;
      }
      word[i] = ch;
      if (mpp.find(word) != mpp.end() && mpp[word] + 1 == steps) {

        seq.push_back(word);
        dfs(word, seq);
        seq.pop_back();
      }
    }

    word[i] = original;
  }
}

vector<vector<string>> ladderLength(string beginWord, string endWord,
                                    vector<string> &wordList) {

  unordered_set<string> st(wordList.begin(), wordList.end());
  queue<string> q;
  beginW = beginWord;
  q.push(beginWord);
  mpp[beginWord] = 1;
  st.erase(beginWord);
  sz = beginWord.size();

  while (!q.empty()) {
    string word = q.front();
    int steps = mpp[word];
    q.pop();
    if (word == endWord) {
      break;
    }
    for (int i = 0; i < sz; i++) {
      char original = word[i];

      for (char ch = 'a'; ch <= 'z'; ch++) {
        word[i] = ch;
        if (st.count(word)) {
          q.push(word);
          st.erase(word);
          mpp[word] = steps + 1;
        }
      }

      word[i] = original;
    }
  }

  if (mpp.find(endWord) != mpp.end()) {
    vector<string> seq;
    seq.push_back(endWord);
    dfs(endWord, seq);
  }

  return ans;
}

int main() {
  cout << "28 G 31 Word Ladder II Optimized Approach Shortest Paths" << endl;

  // step 1 is Use the First Word Ladder way and get the Map with the words with
  // there Levels

  // Step 2 Backtrack from the Final Word and perfrom DFS in recursive manner

  // SO as our Previous Approach Gives us TLE Because it explores and try to
  // store all the paths even which are not valid ones so we get TLE but in here
  // we get to the Level we know know that there are two path that can be
  // reached so we just backtrack those too

  string beginWord = "bat";
  string endWord = "coz";

  vector<string> wordList = {"pat", "bot", "pot", "poz", "coz"};

  /*
      Expected Shortest Sequences:
      ----------------------------

      Path 1:
      bat -> bot -> pot -> poz -> coz

      Path 2:
      bat -> pat -> pot -> poz -> coz

      Both paths are shortest paths
      so we must return BOTH.
  */

  vector<vector<string>> ans = ladderLength(beginWord, endWord, wordList);

  cout << "\nAll Shortest Transformation Sequences:\n\n";

  /*
      Printing all shortest paths
  */

  for (auto sequence : ans) {

    for (int i = 0; i < sequence.size(); i++) {

      cout << sequence[i];

      // Avoid extra arrow after last word
      if (i != sequence.size() - 1) {
        cout << " -> ";
      }
    }

    cout << endl;
  }

  return 0;
}

// // ------------------------------------------------------------
// // DFS Backtracking
// // ------------------------------------------------------------
// // Start from endWord and move backwards.
// //
// // Example:
// //
// // coz(level 5)
// //  -> poz(level 4)
// //      -> pot(level 3)
// //
// // We only move to words having:
// // previousLevel = currentLevel - 1
// //
// // This guarantees shortest paths only.
// // ------------------------------------------------------------
// void dfs(string word, vector<string> &seq) {

//   // Base Case:
//   // We reached the beginWord
//   if (word == beginW) {

//     // Current sequence is reversed
//     // Example:
//     // coz -> poz -> pot -> bot -> bat
//     //
//     // Reverse it to store proper answer
//     reverse(seq.begin(), seq.end());

//     ans.push_back(seq);

//     // Restore original order for backtracking
//     reverse(seq.begin(), seq.end());

//     return;
//   }

//   // Current level of this word
//   int steps = mpp[word];

//   // Try changing every character
//   for (int i = 0; i < sz; i++) {

//     // Store original character
//     char original = word[i];

//     // Try all lowercase letters
//     for (char ch = 'a'; ch <= 'z'; ch++) {

//       // Skip same character
//       if (ch == original) {
//         continue;
//       }

//       // Transform character
//       word[i] = ch;

//       // Valid previous word condition:
//       //
//       // 1. Word exists in BFS map
//       // 2. Its level is exactly one less
//       //
//       // Example:
//       // coz(5) -> poz(4)
//       if (mpp.find(word) != mpp.end() &&
//           mpp[word] + 1 == steps) {

//         // Choose
//         seq.push_back(word);

//         // Explore
//         dfs(word, seq);

//         // Backtrack
//         seq.pop_back();
//       }
//     }

//     // Restore original character
//     word[i] = original;
//   }
// }

// // ------------------------------------------------------------
// // BFS Function
// // ------------------------------------------------------------
// // Finds shortest level of every reachable word
// // from beginWord.
// // ------------------------------------------------------------
// vector<vector<string>> ladderLength(string beginWord,
//                                     string endWord,
//                                     vector<string> &wordList) {

//   // Store all words for O(1) lookup
//   unordered_set<string> st(wordList.begin(),
//                            wordList.end());

//   // Edge Case:
//   // endWord must exist
//   if (!st.count(endWord)) {
//     return {};
//   }

//   // BFS Queue
//   queue<string> q;

//   // Store globally for DFS
//   beginW = beginWord;

//   // Start BFS
//   q.push(beginWord);

//   // beginWord starts at level 1
//   mpp[beginWord] = 1;

//   // Remove visited word
//   st.erase(beginWord);

//   // All words have same size
//   sz = beginWord.size();

//   // --------------------------------------------------------
//   // BFS Traversal
//   // --------------------------------------------------------
//   while (!q.empty()) {

//     string word = q.front();

//     q.pop();

//     // Current level
//     int steps = mpp[word];

//     // Stop once we reach endWord
//     // BFS guarantees shortest path
//     if (word == endWord) {
//       break;
//     }

//     // Try changing every character
//     for (int i = 0; i < sz; i++) {

//       // Store original character
//       char original = word[i];

//       // Try all lowercase letters
//       for (char ch = 'a'; ch <= 'z'; ch++) {

//         // Skip same character
//         if (ch == original) {
//           continue;
//         }

//         // Transform character
//         word[i] = ch;

//         // If transformed word exists
//         if (st.count(word)) {

//           // Push into BFS queue
//           q.push(word);

//           // Remove to avoid revisiting
//           //
//           // Why safe?
//           // ----------
//           // BFS always reaches a node
//           // first time with shortest distance
//           st.erase(word);

//           // Store level
//           mpp[word] = steps + 1;
//         }
//       }

//       // Restore original character
//       word[i] = original;
//     }
//   }

//   // --------------------------------------------------------
//   // DFS Backtracking
//   // --------------------------------------------------------
//   // Only possible if endWord was reached
//   if (mpp.find(endWord) != mpp.end()) {

//     vector<string> seq;

//     // Start from endWord
//     seq.push_back(endWord);

//     // Generate all shortest paths
//     dfs(endWord, seq);
//   }

//   return ans;
// }